### ISSUE TITLE
Versioning system

### ISSUE THREAD

**Issue by lukehedger** [kord-network/docs#11]
Would it be pertinent to add a versioning system to META Network specs? Primarily, this would facilitate future changes to specs and backwards-compatibility for earlier implementations.

For example:
```
metaIdentity: {
  aux: {},
  core: {},
  version: META.Identity.v0
}
```

**Comment by lmars** [comment]
Sounds good to me :+1:

**Comment by MrTibbles** [comment]
Sounds sensible yeah.
